version: "3.8"

services:
  db:
    image: postgres:16
    container_name: my-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: my_app_db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: my-node-app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - DB_NAME=my_app_db
      - DB_PORT=5432
      - CONSUMER_SECRET=${CONSUMER_SECRET}
      - AGENT_ID=${AGENT_ID}
    depends_on:
      - db
    volumes:
      - .:/app
    command: ["npm", "start"]
